---
- hosts: one
  become: yes

  tasks:
  - name: Force cache update
    ansible.builtin.apt:
      update_cache: yes

  - name: Add ansible stable repository from PPA and install its signing key on Ubuntu target
    ansible.builtin.apt_repository:
      repo: ppa:ansible/ansible

  - name: Install default packages
    ansible.builtin.apt: 
      name: "{{ default.apt_pkgs }}"
      state: latest